openapi: 3.1.0
info:
  version: 1.0.0
  title: Recipes API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing and sharing culinary recipes.

tags:
  - name: Auth
    description: User authentication endpoints
  - name: Users
    description: User-related endpoints
  - name: Categories
    description: Recipe categories endpoints
  - name: Ingredients
    description: Recipe ingredients endpoints
  - name: Recipes
    description: Endpoints for managing recipes

servers:
  - url: http://127.0.0.1:3000
    description: Development server

paths:
  /api/categories:
    get:
      $ref: './paths/categories/get.yaml'
  /auth/register:
    post:
      $ref: './paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: './paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: './paths/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: './paths/auth/refresh.yaml'
  /users/me:
    get:
      $ref: './paths/users/getMe.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT authentication scheme

  schemas:
    Recipe:
      $ref: './components/schemas/Recipe.yaml'
    User:
      $ref: './components/schemas/User.yaml'
    Ingredient:
      $ref: './components/schemas/Ingredient.yaml'
    Category:
      $ref: './components/schemas/Category.yaml'
    Session:
      $ref: './components/schemas/Session.yaml'
