openapi: 3.1.0
info:
  version: 1.0.0
  title: Recipes API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing and sharing culinary recipes.

tags:
  - name: Auth
    description: User authentication endpoints
  - name: Users
    description: User-related endpoints
  - name: Categories
    description: Recipe categories endpoints
  - name: Ingredients
    description: Recipe ingredients endpoints
  - name: Recipes
    description: Endpoints for managing recipes

servers:
  - url: http://127.0.0.1:3000
    description: Development server

paths:
  /auth/register:
    post:
      $ref: ./paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ./paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ./paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ./paths/auth/refresh.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT authentication scheme
  schemas:
    recipe:
      $ref: ./components/schemas/Recipe.yaml
    user:
      $ref: ./components/schemas/User.yaml
    ingredient:
      $ref: ./components/schemas/Ingredient.yaml
    category:
      $ref: ./components/schemas/Category.yaml
    session:
      $ref: ./components/schemas/Session.yaml
